spring:
  application:
    name: ms-items
    external-services:
      ms-prodcuts: http://ms-products/api/products

  config:
    import:
      - "classpath:application-logging.yml"

  profiles:
    active: dev   # change to test or prod as needed
  cloud:
    discovery:
      client:
        simple:
          instances:
            ms-products:
              - uri: http://localhost:8081
              - uri: http://localhost:8082

server:
  port: 8080
